[package]
name = "projectm_lambda"
version = "0.1.0"
edition = "2021"

[dependencies]
gstreamer = "0.22.6"
gstreamer-audio = "0.22.6"
gstreamer-video = "0.22.6"
gstreamer-app = "0.22.6"
anyhow = "1.0"
tokio = { version = "1", features = ["full"] }
env_logger = "0.11"
log = "0.4"
